In [3]:
import pandas as pd

import os

os.chdir(r"D:\dataverse_files\Sample")

# Create four sample dataframes
df1 = pd.read_csv('2005sample.csv')
df2 = pd.read_csv('2006sample.csv')
df3 = pd.read_csv('2007sample.csv')
df4 = pd.read_csv('2008sample.csv')

# Merge the dataframes using pd.concat()
merged_df = pd.concat([df1, df2, df3, df4], axis=0)

# Print the merged dataframe
print(merged_df)

     Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0    2005      9          26          1   1000.0        1009   1122.0
1    2005     10          26          3   1307.0        1317   1319.0
2    2005      9          10          6   2114.0        2119   2159.0
3    2005      9          23          5   2052.0        2030   2212.0
4    2005      3          19          6   1852.0        1855   2400.0
..    ...    ...         ...        ...      ...         ...      ...
995  2008      2          20          3   1840.0        1800   1932.0
996  2008      1           6          7    620.0         620   1132.0
997  2008      1           6          7   1031.0        1034   1614.0
998  2008      2           9          6    832.0         840   1058.0
999  2008      3           4          2   1955.0        1845   2037.0

     CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0          1129            OH       5576  ...   12.0      8.0          0
1          1343            OO       6706  ...    6.0      7.0          0
2          2159            OO       6052  ...    5.0     11.0          0
3          2149            UA        593  ...    5.0     14.0          0
4            22            UA         68  ...    5.0     10.0          0
..          ...           ...        ...  ...    ...      ...        ...
995        1900            WN       2620  ...    4.0      7.0          0
996        1150            AA       1452  ...    8.0     11.0          0
997        1600            UA       1460  ...    2.0     40.0          0
998        1124            EV       4651  ...    5.0      8.0          0
999        2400            9E       5841  ...   16.5     31.0          0

     Diverted  CarrierDelay  WeatherDelay   NASDelay SecurityDelay  \
0           0          0.00           0.0   0.000000           0.0
1           0          0.00           0.0   0.000000           0.0
2           0          0.00           0.0   0.000000           0.0
3           0          0.00           0.0   1.000000           0.0
4           0          0.00           0.0   0.000000           0.0
..        ...           ...           ...        ...           ...
995         0         32.00           0.0   0.000000           0.0
996         0          4.50           0.0  14.142857           0.0
997         0          5.25           0.0  12.750000           0.0
998         0          3.50           0.0  14.500000           0.0
999         1          0.00           0.0  24.500000           0.0

     LateAircraftDelay  Delay
0                 0.00      N
1                 0.00      N
2                 0.00      N
3                22.00      Y
4                 0.00      N
..                 ...    ...
995               0.00      Y
996               0.00      N
997              21.00      Y
998               0.00      N
999               5.25      Y

[4000 rows x 29 columns]

In [6]:
merged_df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay
0,2005,9,26,1,1000.0,1009,1122.0,1129,OH,5576,...,12.0,8.0,0,0,0.00,0.0,0.000000,0.0,0.00,N
1,2005,10,26,3,1307.0,1317,1319.0,1343,OO,6706,...,6.0,7.0,0,0,0.00,0.0,0.000000,0.0,0.00,N
2,2005,9,10,6,2114.0,2119,2159.0,2159,OO,6052,...,5.0,11.0,0,0,0.00,0.0,0.000000,0.0,0.00,N
3,2005,9,23,5,2052.0,2030,2212.0,2149,UA,593,...,5.0,14.0,0,0,0.00,0.0,1.000000,0.0,22.00,Y
4,2005,3,19,6,1852.0,1855,2400.0,22,UA,68,...,5.0,10.0,0,0,0.00,0.0,0.000000,0.0,0.00,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2008,2,20,3,1840.0,1800,1932.0,1900,WN,2620,...,4.0,7.0,0,0,32.00,0.0,0.000000,0.0,0.00,Y
996,2008,1,6,7,620.0,620,1132.0,1150,AA,1452,...,8.0,11.0,0,0,4.50,0.0,14.142857,0.0,0.00,N
997,2008,1,6,7,1031.0,1034,1614.0,1600,UA,1460,...,2.0,40.0,0,0,5.25,0.0,12.750000,0.0,21.00,Y
998,2008,2,9,6,832.0,840,1058.0,1124,EV,4651,...,5.0,8.0,0,0,3.50,0.0,14.500000,0.0,0.00,N
999,2008,3,4,2,1955.0,1845,2037.0,2400,9E,5841,...,16.5,31.0,0,1,0.00,0.0,24.500000,0.0,5.25,Y

In [7]:
# save the DataFrame to a CSV file
merged_df.to_csv("Dataset.csv", index=False)

# Thank You